"""initial_schema

Revision ID: 1dcf46b0e017
Revises: 
Create Date: 2026-02-09 03:20:13.921149+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dcf46b0e017'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('spawn_enabled', sa.Boolean(), nullable=False),
    sa.Column('spawn_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('spawn_threshold', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_spawn_at', sa.DateTime(), nullable=True),
    sa.Column('redirect_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('battles_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_spawns', sa.Integer(), nullable=False),
    sa.Column('total_catches', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_groups'))
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_lower', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('is_purchasable', sa.Boolean(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('is_holdable', sa.Boolean(), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sprite_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_name_lower'), 'items', ['name_lower'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_lower', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('effect_chance', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=30), nullable=False),
    sa.Column('crit_rate', sa.Integer(), nullable=False),
    sa.Column('makes_contact', sa.Boolean(), nullable=False),
    sa.Column('is_sound_based', sa.Boolean(), nullable=False),
    sa.Column('is_punch', sa.Boolean(), nullable=False),
    sa.Column('is_bite', sa.Boolean(), nullable=False),
    sa.Column('is_pulse', sa.Boolean(), nullable=False),
    sa.Column('is_recharge', sa.Boolean(), nullable=False),
    sa.Column('is_charge', sa.Boolean(), nullable=False),
    sa.Column('is_protect', sa.Boolean(), nullable=False),
    sa.Column('is_reflectable', sa.Boolean(), nullable=False),
    sa.Column('is_snatchable', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moves'))
    )
    op.create_index(op.f('ix_moves_name'), 'moves', ['name'], unique=False)
    op.create_index(op.f('ix_moves_name_lower'), 'moves', ['name_lower'], unique=False)
    op.create_table('pokemon_learnsets',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('learn_method', sa.String(length=20), nullable=False),
    sa.Column('level_learned', sa.Integer(), nullable=True),
    sa.Column('version_group', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('species_id', 'move_id', 'learn_method', name=op.f('pk_pokemon_learnsets'))
    )
    op.create_table('pokemon_species',
    sa.Column('national_dex', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_lower', sa.String(length=50), nullable=False),
    sa.Column('type1', sa.String(length=20), nullable=False),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_sp_attack', sa.Integer(), nullable=False),
    sa.Column('base_sp_defense', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('abilities', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('hidden_ability', sa.String(length=50), nullable=True),
    sa.Column('catch_rate', sa.Integer(), nullable=False),
    sa.Column('base_friendship', sa.Integer(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('growth_rate', sa.String(length=30), nullable=False),
    sa.Column('gender_ratio', sa.Float(), nullable=True),
    sa.Column('egg_groups', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('hatch_counter', sa.Integer(), nullable=False),
    sa.Column('evolution_chain_id', sa.Integer(), nullable=True),
    sa.Column('evolves_from_species_id', sa.Integer(), nullable=True),
    sa.Column('sprite_url', sa.Text(), nullable=True),
    sa.Column('sprite_shiny_url', sa.Text(), nullable=True),
    sa.Column('sprite_back_url', sa.Text(), nullable=True),
    sa.Column('sprite_back_shiny_url', sa.Text(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('is_baby', sa.Boolean(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('national_dex', name=op.f('pk_pokemon_species'))
    )
    op.create_index(op.f('ix_pokemon_species_name'), 'pokemon_species', ['name'], unique=False)
    op.create_index(op.f('ix_pokemon_species_name_lower'), 'pokemon_species', ['name_lower'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('user1_id', sa.BigInteger(), nullable=False),
    sa.Column('user2_id', sa.BigInteger(), nullable=False),
    sa.Column('user1_pokemon_count', sa.Integer(), nullable=False),
    sa.Column('user2_pokemon_count', sa.Integer(), nullable=False),
    sa.Column('user1_coins', sa.BigInteger(), nullable=False),
    sa.Column('user2_coins', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_history'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily', sa.DateTime(), nullable=True),
    sa.Column('selected_pokemon_id', sa.String(length=36), nullable=True),
    sa.Column('shiny_hunt_species_id', sa.Integer(), nullable=True),
    sa.Column('shiny_hunt_chain', sa.Integer(), nullable=False),
    sa.Column('battle_wins', sa.Integer(), nullable=False),
    sa.Column('battle_losses', sa.Integer(), nullable=False),
    sa.Column('battle_rating', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_users'))
    )
    op.create_table('active_spawns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('is_shiny', sa.Boolean(), nullable=False),
    sa.Column('spawned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('caught_by', sa.BigInteger(), nullable=True),
    sa.Column('caught_at', sa.DateTime(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caught_by'], ['users.telegram_id'], name=op.f('fk_active_spawns_caught_by_users')),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], name=op.f('fk_active_spawns_chat_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.national_dex'], name=op.f('fk_active_spawns_species_id_pokemon_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_spawns'))
    )
    op.create_index(op.f('ix_active_spawns_chat_id'), 'active_spawns', ['chat_id'], unique=False)
    op.create_table('battles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player1_id', sa.BigInteger(), nullable=False),
    sa.Column('player2_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('player1_team', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('player2_team', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('player1_active_index', sa.Integer(), nullable=False),
    sa.Column('player2_active_index', sa.Integer(), nullable=False),
    sa.Column('battle_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('whose_turn', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'FORFEITED', name='battlestatus'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('battle_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('winner_coins', sa.Integer(), nullable=False),
    sa.Column('winner_xp', sa.Integer(), nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('rating_change_p1', sa.Integer(), nullable=True),
    sa.Column('rating_change_p2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.telegram_id'], name=op.f('fk_battles_player1_id_users')),
    sa.ForeignKeyConstraint(['player2_id'], ['users.telegram_id'], name=op.f('fk_battles_player2_id_users')),
    sa.ForeignKeyConstraint(['winner_id'], ['users.telegram_id'], name=op.f('fk_battles_winner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_battles'))
    )
    op.create_index(op.f('ix_battles_player1_id'), 'battles', ['player1_id'], unique=False)
    op.create_index(op.f('ix_battles_player2_id'), 'battles', ['player2_id'], unique=False)
    op.create_index(op.f('ix_battles_status'), 'battles', ['status'], unique=False)
    op.create_table('inventory_items',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_inventory_items_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_inventory_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('pk_inventory_items'))
    )
    op.create_table('pokedex_entries',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('caught', sa.Boolean(), nullable=False),
    sa.Column('caught_shiny', sa.Boolean(), nullable=False),
    sa.Column('times_caught', sa.Integer(), nullable=False),
    sa.Column('first_caught_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.national_dex'], name=op.f('fk_pokedex_entries_species_id_pokemon_species')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_pokedex_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'species_id', name=op.f('pk_pokedex_entries'))
    )
    op.create_table('pokemon',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.BigInteger(), nullable=False),
    sa.Column('iv_hp', sa.Integer(), nullable=False),
    sa.Column('iv_attack', sa.Integer(), nullable=False),
    sa.Column('iv_defense', sa.Integer(), nullable=False),
    sa.Column('iv_sp_attack', sa.Integer(), nullable=False),
    sa.Column('iv_sp_defense', sa.Integer(), nullable=False),
    sa.Column('iv_speed', sa.Integer(), nullable=False),
    sa.Column('ev_hp', sa.Integer(), nullable=False),
    sa.Column('ev_attack', sa.Integer(), nullable=False),
    sa.Column('ev_defense', sa.Integer(), nullable=False),
    sa.Column('ev_sp_attack', sa.Integer(), nullable=False),
    sa.Column('ev_sp_defense', sa.Integer(), nullable=False),
    sa.Column('ev_speed', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=20), nullable=False),
    sa.Column('ability', sa.String(length=50), nullable=True),
    sa.Column('ability_slot', sa.Integer(), nullable=False),
    sa.Column('is_shiny', sa.Boolean(), nullable=False),
    sa.Column('moves', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('held_item', sa.String(length=50), nullable=True),
    sa.Column('friendship', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_on_market', sa.Boolean(), nullable=False),
    sa.Column('is_in_trade', sa.Boolean(), nullable=False),
    sa.Column('original_trainer_id', sa.BigInteger(), nullable=True),
    sa.Column('caught_at', sa.DateTime(), nullable=False),
    sa.Column('caught_in_group_id', sa.BigInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('form', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.telegram_id'], name=op.f('fk_pokemon_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.national_dex'], name=op.f('fk_pokemon_species_id_pokemon_species')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon'))
    )
    op.create_index(op.f('ix_pokemon_owner_id'), 'pokemon', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pokemon_species_id'), 'pokemon', ['species_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user1_id', sa.BigInteger(), nullable=False),
    sa.Column('user2_id', sa.BigInteger(), nullable=False),
    sa.Column('user1_pokemon_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('user2_pokemon_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('user1_coins', sa.BigInteger(), nullable=False),
    sa.Column('user2_coins', sa.BigInteger(), nullable=False),
    sa.Column('user1_confirmed', sa.Boolean(), nullable=False),
    sa.Column('user2_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED_ONE', 'COMPLETED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.telegram_id'], name=op.f('fk_trades_user1_id_users')),
    sa.ForeignKeyConstraint(['user2_id'], ['users.telegram_id'], name=op.f('fk_trades_user2_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index(op.f('ix_trades_user1_id'), 'trades', ['user1_id'], unique=False)
    op.create_index(op.f('ix_trades_user2_id'), 'trades', ['user2_id'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'CANCELLED', 'EXPIRED', name='listingstatus'), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.telegram_id'], name=op.f('fk_market_listings_buyer_id_users')),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_market_listings_pokemon_id_pokemon')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.telegram_id'], name=op.f('fk_market_listings_seller_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_listings')),
    sa.UniqueConstraint('pokemon_id', name=op.f('uq_market_listings_pokemon_id'))
    )
    op.create_index(op.f('ix_market_listings_seller_id'), 'market_listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_market_listings_status'), 'market_listings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_listings_status'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_seller_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_trades_user2_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_user1_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_pokemon_species_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_owner_id'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_table('pokedex_entries')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_battles_status'), table_name='battles')
    op.drop_index(op.f('ix_battles_player2_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_player1_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_active_spawns_chat_id'), table_name='active_spawns')
    op.drop_table('active_spawns')
    op.drop_table('users')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_pokemon_species_name_lower'), table_name='pokemon_species')
    op.drop_index(op.f('ix_pokemon_species_name'), table_name='pokemon_species')
    op.drop_table('pokemon_species')
    op.drop_table('pokemon_learnsets')
    op.drop_index(op.f('ix_moves_name_lower'), table_name='moves')
    op.drop_index(op.f('ix_moves_name'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_items_name_lower'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_table('groups')
    # ### end Alembic commands ###
