"""add teams table and user team_id FK

Revision ID: 4409951490dd
Revises: aa6e206e3560
Create Date: 2026-02-12 03:58:52.664338+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4409951490dd'
down_revision: Union[str, None] = 'aa6e206e3560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tag', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.BigInteger(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name='uq_teams_name'),
    sa.UniqueConstraint('tag', name='uq_teams_tag')
    )
    op.add_column('users', sa.Column('team_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('team_role', sa.String(length=20), nullable=True))
    op.create_foreign_key(op.f('fk_users_team_id_teams'), 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_team_id_teams'), 'users', type_='foreignkey')
    op.drop_column('users', 'team_role')
    op.drop_column('users', 'team_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
