"""add breeding tables

Revision ID: aa6e206e3560
Revises: 35f1cfb840fa
Create Date: 2026-02-12 02:21:46.840109+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6e206e3560'
down_revision: Union[str, None] = '35f1cfb840fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_eggs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('parent1_id', sa.UUID(), nullable=True),
    sa.Column('parent2_id', sa.UUID(), nullable=True),
    sa.Column('iv_hp', sa.Integer(), nullable=False),
    sa.Column('iv_attack', sa.Integer(), nullable=False),
    sa.Column('iv_defense', sa.Integer(), nullable=False),
    sa.Column('iv_sp_attack', sa.Integer(), nullable=False),
    sa.Column('iv_sp_defense', sa.Integer(), nullable=False),
    sa.Column('iv_speed', sa.Integer(), nullable=False),
    sa.Column('steps_remaining', sa.Integer(), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('is_shiny', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pokemon_species.national_dex'], name=op.f('fk_pokemon_eggs_species_id_pokemon_species')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_pokemon_eggs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon_eggs'))
    )
    op.create_index(op.f('ix_pokemon_eggs_user_id'), 'pokemon_eggs', ['user_id'], unique=False)
    op.create_table('daycare_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_daycare_slots_pokemon_id_pokemon'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_daycare_slots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daycare_slots'))
    )
    op.create_index(op.f('ix_daycare_slots_user_id'), 'daycare_slots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daycare_slots_user_id'), table_name='daycare_slots')
    op.drop_table('daycare_slots')
    op.drop_index(op.f('ix_pokemon_eggs_user_id'), table_name='pokemon_eggs')
    op.drop_table('pokemon_eggs')
    # ### end Alembic commands ###
