"""add wonder trade

Revision ID: 06107b46c7b5
Revises: 96f3f6b587aa
Create Date: 2026-02-10 23:17:38.102662+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06107b46c7b5'
down_revision: Union[str, None] = '96f3f6b587aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wonder_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('species_name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_shiny', sa.Boolean(), nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('matched_with_id', sa.UUID(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_wonder_trades_pokemon_id_pokemon'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_wonder_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wonder_trades'))
    )
    op.create_index(op.f('ix_wonder_trades_is_matched'), 'wonder_trades', ['is_matched'], unique=False)
    op.create_index(op.f('ix_wonder_trades_user_id'), 'wonder_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wonder_trades_user_id'), table_name='wonder_trades')
    op.drop_index(op.f('ix_wonder_trades_is_matched'), table_name='wonder_trades')
    op.drop_table('wonder_trades')
    # ### end Alembic commands ###
