"""add permissions column to spawn_admins

Revision ID: 7834db8072fb
Revises: 4409951490dd
Create Date: 2026-02-15 04:30:45.769529+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7834db8072fb'
down_revision: Union[str, None] = '4409951490dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spawn_admins', sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spawn_admins', 'permissions')
    # ### end Alembic commands ###
